title: Isacco Beretta
url: "https://isaccoberetta.github.io"
baseurl: "https://isaccoberetta.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/Isacco Beretta/"
 - name: "CV"
   link: "CVeng.pdf"
 - name: "Contact"
   link: "contact"
